### ISSUE TITLE
Error: The XML you provided was not well-formed or did not validate against our published schema

### ISSUE THREAD

**Issue by serverlesspolska** [getlift/lift#133]
During `sls deploy` of react/gatsby website I get the following error:
```
[...]
Deleting public/static/slide-3-ac5bf32331347fc3e267e58177c3bccc.png
Deleting public/static/white_bg1-4a8b4ddfca1d3b974210bfebf741f1e5.svg
Deleting public/styles.332ed04b92590be19262.css
Deleting public/styles.55e29f7ac37d141a5e6a.css
Deleting public/webpack-runtime-b6adb77e9e7bb73d8646.js
Deleting public/webpack-runtime-b6adb77e9e7bb73d8646.js.map
Deleting public/webpack-runtime-d682f7d47c0dd90b1df7.js
Deleting public/webpack-runtime-d682f7d47c0dd90b1df7.js.map
Deleting public/webpack.stats.json

Serverless Error ----------------------------------------
 
  The XML you provided was not well-formed or did not validate against our published schema
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.1
     Framework Version:         2.64.1 (local)
     Plugin Version:            5.5.0
     SDK Version:               4.3.0
     Components Version:        3.17.1
```

Perhaps it is that problem: https://stackoverflow.com/a/69235576/4105584

**Comment by fredericbarthelet** [comment]
Hey @serverlesspolska, thanks for submitting your issue.

This error happens when too many files need to be deleted on the s3 bucket holding your static website.

This is mostly due to previous delete operation from previous deployment silently failing.

This behavior has been fixed in https://github.com/getlift/lift/pull/115

Please ensure your deployment user has s3:deleteObject permissions, update to latest Lift version, delete all files in s3 bucket manually using the web console and try again.

Let me know if the problem still happens after that. Sorry for your trouble.

**Comment by shengslogar** [comment]
Just because this issue is still open — wanted to note that I encountered this when an ultimately failing `sls remove` run successfully emptied out my assets bucket. Subsequent `sls remove`s immediately failed with this message unless I manually uploaded a file to or created a folder in my bucket to be removed.

**Comment by gilbitron** [comment]
I'm also getting this issue. We have a lot of assets in our deployments. Apparently, S3 has a batch delete limit of 1000 files.

**Comment by mnapoli** [comment]
Fixed in #400

**Comment by shengslogar** [comment]
Thanks! Eyeballing the PR doesn’t look like this would solve my previous problem of delete running when there are no files present. Should I create a separate issue/PR for that?

**Comment by mnapoli** [comment]
@shengslogar yes please :)
